services:
  _defaults:
    autowire: true
    public: true

  App\ApiV1Bundle\SpecificationController:
  App\ApiV1Bundle\RequestHandler:
  App\ApiV1Bundle\Helpers\ApiDependencies:
  App\ApiV1Bundle\Helpers\Validator:
