#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api-specification:
  path:       /api/v1/
  defaults:   { _controller: 'App\ApiV1Bundle\SpecificationController::showReadableJson' }

openApi:
  path:       /api/v1/specifications.json
  defaults:   { _controller: 'App\ApiV1Bundle\SpecificationController::show' }
