api-landing-page:
  path: /
  defaults: { _controller: 'App\Controller\ApiController:handle' }

api-v1-docs:
  path:       /v1/
  defaults:   { _controller: 'App\ApiV1Bundle\SpecificationController:showDocs' }

api-v1-pretty-json:
  path:       /v1/specs.json
  defaults:   { _controller: 'App\ApiV1Bundle\SpecificationController:showReadableSpecs' }

api-v1-json-docs:
  path:       /v1/specifications.json
  defaults:   { _controller: 'App\ApiV1Bundle\SpecificationController::show' }
